### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by grauJavier** [grauJavier/catalog-of-my-things-ruby#28]
### GitHub Project Link
- https://github.com/grauJavier/catalog-of-my-things-ruby/projects/1

### Assignees
In our group, there are 4 members in total. Our assignments are distributed as: 
- **Team member 1:** Daniel Morillo @danifromecuador 
- **Team member 2:** Javier Grau @grauJavier 
- **Team member 3:** Ali Baba Hussaini @Alibaba2023 
- **Team member 4:** Lawrence Kioko @Kidd254 

🌟 Thanks for your kind review 🌟

**Comment by LionRouge1** [comment]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

## Highlights
- Great job, setting up the task for each member :100: 
- Nice work you meet all the requirements :1st_place_medal: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
